function [divf] = explicit_1deriv_fourthorder (f,inp)
%     a = 2;
%     b=-1;
%     divf=a*( f(inp.V1+3:inp.VN+3) -9*f(inp.V1+1:inp.VN+1) + 16*f(inp.V1:inp.VN) - ...
%         9*f(inp.V1-1:inp.VN-1) + f(inp.V1-3:inp.VN-3))/(6*inp.DELTA_X^4) + ...
%         b*( f(inp.V1+2:inp.VN+2) -4*f(inp.V1+1:inp.VN+1) +6*f(inp.V1:inp.VN) - ...
%         4*f(inp.V1-1:inp.VN-1) + f(inp.V1-2:inp.VN-2))/inp.DELTA_X^4;
    
      divf= ( -1/6*(f(inp.V1-3:inp.VN-3)+f(inp.V1+3:inp.VN+3)) + ...
                2* (f(inp.V1-2:inp.VN-2)+f(inp.V1+2:inp.VN+2)) - ...
              13/2*(f(inp.V1-1:inp.VN-1)+f(inp.V1+1:inp.VN+1)) + ...
              28/3*f(inp.V1:inp.VN) ) / inp.DELTA_X^4;
          
%       divf= ( -1/2*(f(inp.V1-3:inp.VN-3)-f(inp.V1+3:inp.VN+3)) + ...
%               2* (f(inp.V1-2:inp.VN-2)-f(inp.V1+2:inp.VN+2)) - ...
%               5/2*(f(inp.V1-1:inp.VN-1)-f(inp.V1+1:inp.VN+1)) + ...
%               0*f(inp.V1:inp.VN) ) / inp.DELTA_X^5;
end